### PR TITLE
feat: :arrow_up: GoReleaser 0.157.0 -> 1.7.0

### PR DESCRIPTION
**Pull request by mhornbacher**
This was tested locally and resolves issue #185 

Locally bin folder was created for m1 mac

### CODE REVIEW

**Comment by jradtilbrook** [comment]
Thanks for this @mhornbacher. I'd like to review the changelog for GoReleaser just in case there are any gotchas. I'm hoping to get around to this next week

**Comment by mhornbacher** [comment]
Awesome!

**Review by jradtilbrook — APPROVED** [review]
This looks to have fixed it 👍 

Thanks for helping out @mhornbacher

**Comment by mhornbacher** [comment]
ofc, thanks for merging in!

**Pull request merged**
