### PR TITLE
SUP-1696: Add golangci-lint 

### PR DESCRIPTION
**Pull request by lizrabuya**
ci: Add support for golangci-lint

## PR checklist:
- [ ] `docs/` updated  <-- No need for a doc update, no user impact
- [ ] tests added <-- Tests not applicable for this change 
- [x] `CHANGELOG.md` updated with pending release information

### CODE REVIEW

**Review by jradtilbrook — COMMENTED** [review]
Nice, its not too hard to add 👍 

Can you check out SUP-1690 and see if there are settings for golangci-lint that would find code not checking for nil pointers and enable that as well

**Comment by jradtilbrook** [comment]
Looks like that doesn't exist so then this looks good 👍

**Review by jradtilbrook — DISMISSED** [review]

**Review by james2791 — DISMISSED** [review]
🚢

**Comment by lizrabuya** [comment]
> Nice, its not too hard to add 👍
> 
> Can you check out SUP-1690 and see if there are settings for golangci-lint that would find code not checking for nil pointers and enable that as well

@jradtilbrook , I'm afraid the issue with SUP-1690 is something that can not be detected from a linter. The [staticcheck](https://staticcheck.dev) linter can only deduce a possible nil pointer dereference. This linter is enabled by default in golangci-lint.

**Review by jradtilbrook — APPROVED** [review]

**Pull request merged**
