### PR TITLE
Fix various argument and attribute docs

### PR DESCRIPTION
**Pull request by lachlancooper**
This adds the `id` attribute for the `pipeline` data source that was missing from the docs. This is useful for passing to the `pipeline_schedule` resource if the pipeline itself is managed elsewhere.

This also adds boilerplate intro sentences to every argument and attribute header, as with other Terraform providers, to help remind users that arguments can also be used as export attributes.

Finally, this documents the available options for some `team` resource attributes, and fixes various trivial typos and formatting issues.

### CODE REVIEW

**Comment by lachlancooper** [comment]
Closing due to lack of review activity. I'm happy to resolve conflicts if the maintainers want to merge this, but I haven't seen any indication of that as yet.

**Comment by jradtilbrook** [comment]
There's been a few additions recently that are lacking the docs I think so we do need a bit of attention. Sorry for the silence though!

We are happy to accept a contribution like this, it just fell through the cracks. If you want to open it again we should be able to get to it in the next few weeks.

**Comment by lachlancooper** [comment]
> We are happy to accept a contribution like this, it just fell through the cracks. If you want to open it again we should be able to get to it in the next few weeks.

Got it, thanks for the update. I've fixed the merge conflict so this should be ready to go.

**Comment by lachlancooper** [comment]
Closing due to inactivity.

**Pull request closed without merging**
