### PR TITLE
Add allowRebuilds to cluster mutations

### PR DESCRIPTION
**Pull request by jradtilbrook**
This fixes the issue with missing mutation arguments when also using clusters

### CODE REVIEW

**Review by jayco — COMMENTED** [review]
LGTM - have you tested it?

- It won't break things for folks using the current/older version
- It does the thing as expected

**Review by jayco — APPROVED** [review]

**Comment by jradtilbrook** [comment]
Closes #199

**Comment by jradtilbrook** [comment]
I think there is an issue with the REST API around clusters that is blocking this. I'm confirming and following up on that before adding tests here

**Comment by jradtilbrook** [comment]
@jayco turns out the error was my bad copy paste. I've fixed it up now and added acceptance tests to verify this is fixed. Can you have another look?

**Review by jayco — APPROVED** [review]
Going over this at a high level - LGTM! 🎉

Just a question, not a blocker - I love the tests, are we just testing just the happy path? Do we eventually need to add-in any other paths?

**Comment by jradtilbrook** [comment]
@jayco yeah I think the tests could do with some TLC. We have some work scheduled to go over the testing stuff later. I was just shoehorning stuff in for now and tackling a revamp in a future cycle

**Pull request merged**
