### PR TITLE
SUP-1432 v1.0 documentation updates

### PR DESCRIPTION
**Pull request by jradtilbrook**

### CODE REVIEW

**Comment by jradtilbrook** [comment]
How do we feel about keeping the changelog minimal and link out to the upgrade guide on the terraform registry instead? @james2791 @mcncl

**Comment by james2791** [comment]
> How do we feel about keeping the changelog minimal and link out to the upgrade guide on the terraform registry instead? @james2791 @mcncl

Its probably better that way given all the other guides are there too for resources/DSes etc. I had a [draft](https://github.com/buildkite/terraform-provider-buildkite/pull/405) PR for this too but probably can be closed off with this I think @jradtilbrook

**Comment by mcncl** [comment]
My view on it is that upgrading is mutually exclusive to the changelog. Folks will use the changelog to see, well, what's changed. They wouldn't use it to see how they would go about upgrading.

I think any and all changes that in some way adjust the functionality of the application should be listed.

**Review by mcncl — APPROVED** [review]

**Review by james2791 — APPROVED** [review]
👍

**Review by mcncl — APPROVED** [review]

**Review by james2791 — APPROVED** [review]

**Pull request merged**
